export const COUNTRIES = [
    { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', lat: 33.9, lng: 67.7 },
    { name: 'Albania', code: 'AL', flag: '🇦🇱', lat: 41.1, lng: 20.1 },
    { name: 'Algeria', code: 'DZ', flag: '🇩🇿', lat: 28.0, lng: 1.6 },
    { name: 'Andorra', code: 'AD', flag: '🇦🇩', lat: 42.5, lng: 1.5 },
    { name: 'Argentina', code: 'AR', flag: '🇦🇷', lat: -38.4, lng: -63.6 },
    { name: 'Armenia', code: 'AM', flag: '🇦🇲', lat: 40.0, lng: 45.0 },
    { name: 'Australia', code: 'AU', flag: '🇦🇺', lat: -25.2, lng: 133.7 },
    { name: 'Austria', code: 'AT', flag: '🇦🇹', lat: 47.5, lng: 14.5 },
    { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', lat: 40.1, lng: 47.5 },
    { name: 'Bahamas', code: 'BS', flag: '🇧🇸', lat: 25.0, lng: -77.3 },
    { name: 'Bahrain', code: 'BH', flag: '🇧🇭', lat: 26.0, lng: 50.5 },
    { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', lat: 23.7, lng: 90.3 },
    { name: 'Barbados', code: 'BB', flag: '🇧🇧', lat: 13.1, lng: -59.5 },
    { name: 'Belgium', code: 'BE', flag: '🇧🇪', lat: 50.5, lng: 4.4 },
    { name: 'Belize', code: 'BZ', flag: '🇧🇿', lat: 17.1, lng: -88.4 },
    { name: 'Bhutan', code: 'BT', flag: '🇧🇹', lat: 27.5, lng: 90.4 },
    { name: 'Bolivia', code: 'BO', flag: '🇧🇴', lat: -16.2, lng: -63.5 },
    { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', lat: 43.9, lng: 17.6 },
    { name: 'Botswana', code: 'BW', flag: '🇧🇼', lat: -22.3, lng: 24.6 },
    { name: 'Brazil', code: 'BR', flag: '🇧🇷', lat: -14.2, lng: -51.9 },
    { name: 'Brunei', code: 'BN', flag: '🇧🇳', lat: 4.5, lng: 114.7 },
    { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', lat: 42.7, lng: 25.4 },
    { name: 'Cambodia', code: 'KH', flag: '🇰🇭', lat: 12.5, lng: 104.9 },
    { name: 'Cameroon', code: 'CM', flag: '🇨🇲', lat: 7.3, lng: 12.3 },
    { name: 'Canada', code: 'CA', flag: '🇨🇦', lat: 56.1, lng: -106.3 },
    { name: 'Cape Verde', code: 'CV', flag: '🇨🇻', lat: 16.0, lng: -24.0 },
    { name: 'Chile', code: 'CL', flag: '🇨🇱', lat: -35.6, lng: -71.5 },
    { name: 'China', code: 'CN', flag: '🇨🇳', lat: 35.8, lng: 104.1 },
    { name: 'Colombia', code: 'CO', flag: '🇨🇴', lat: 4.5, lng: -74.2 },
    { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', lat: 9.7, lng: -83.7 },
    { name: 'Croatia', code: 'HR', flag: '🇭🇷', lat: 45.1, lng: 15.2 },
    { name: 'Cuba', code: 'CU', flag: '🇨🇺', lat: 21.5, lng: -77.7 },
    { name: 'Cyprus', code: 'CY', flag: '🇨🇾', lat: 35.1, lng: 33.4 },
    { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', lat: 49.8, lng: 15.4 },
    { name: 'Denmark', code: 'DK', flag: '🇩🇰', lat: 56.2, lng: 9.5 },
    { name: 'Dominican Republic', code: 'DO', flag: '🇩🇴', lat: 18.7, lng: -70.1 },
    { name: 'Ecuador', code: 'EC', flag: '🇪🇨', lat: -1.8, lng: -78.1 },
    { name: 'Egypt', code: 'EG', flag: '🇪🇬', lat: 26.8, lng: 30.8 },
    { name: 'El Salvador', code: 'SV', flag: '🇸🇻', lat: 13.7, lng: -88.8 },
    { name: 'Estonia', code: 'EE', flag: '🇪🇪', lat: 58.5, lng: 25.0 },
    { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', lat: 9.1, lng: 40.4 },
    { name: 'Fiji', code: 'FJ', flag: '🇫🇯', lat: -17.7, lng: 178.0 },
    { name: 'Finland', code: 'FI', flag: '🇫🇮', lat: 61.9, lng: 25.7 },
    { name: 'France', code: 'FR', flag: '🇫🇷', lat: 46.2, lng: 2.2 },
    { name: 'Georgia', code: 'GE', flag: '🇬🇪', lat: 42.3, lng: 43.3 },
    { name: 'Germany', code: 'DE', flag: '🇩🇪', lat: 51.1, lng: 10.4 },
    { name: 'Ghana', code: 'GH', flag: '🇬🇭', lat: 7.9, lng: -1.0 },
    { name: 'Greece', code: 'GR', flag: '🇬🇷', lat: 39.0, lng: 21.8 },
    { name: 'Guatemala', code: 'GT', flag: '🇬🇹', lat: 15.7, lng: -90.2 },
    { name: 'Honduras', code: 'HN', flag: '🇭🇳', lat: 15.2, lng: -86.2 },
    { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', lat: 22.3, lng: 114.1 },
    { name: 'Hungary', code: 'HU', flag: '🇭🇺', lat: 47.1, lng: 19.5 },
    { name: 'Iceland', code: 'IS', flag: '🇮🇸', lat: 64.9, lng: -19.0 },
    { name: 'India', code: 'IN', flag: '🇮🇳', lat: 20.5, lng: 78.9 },
    { name: 'Indonesia', code: 'ID', flag: '🇮🇩', lat: -0.7, lng: 113.9 },
    { name: 'Iran', code: 'IR', flag: '🇮🇷', lat: 32.4, lng: 53.6 },
    { name: 'Iraq', code: 'IQ', flag: '🇮🇶', lat: 33.2, lng: 43.6 },
    { name: 'Ireland', code: 'IE', flag: '🇮🇪', lat: 53.1, lng: -8.2 },
    { name: 'Israel', code: 'IL', flag: '🇮🇱', lat: 31.0, lng: 34.8 },
    { name: 'Italy', code: 'IT', flag: '🇮🇹', lat: 41.8, lng: 12.5 },
    { name: 'Jamaica', code: 'JM', flag: '🇯🇲', lat: 18.1, lng: -77.2 },
    { name: 'Japan', code: 'JP', flag: '🇯🇵', lat: 36.2, lng: 138.2 },
    { name: 'Jordan', code: 'JO', flag: '🇯🇴', lat: 30.5, lng: 36.2 },
    { name: 'Kenya', code: 'KE', flag: '🇰🇪', lat: -0.0, lng: 37.9 },
    { name: 'Kuwait', code: 'KW', flag: '🇰🇼', lat: 29.3, lng: 47.4 },
    { name: 'Laos', code: 'LA', flag: '🇱🇦', lat: 19.8, lng: 102.4 },
    { name: 'Latvia', code: 'LV', flag: '🇱🇻', lat: 56.8, lng: 24.6 },
    { name: 'Lebanon', code: 'LB', flag: '🇱🇧', lat: 33.8, lng: 35.8 },
    { name: 'Lithuania', code: 'LT', flag: '🇱🇹', lat: 55.1, lng: 23.8 },
    { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', lat: 49.8, lng: 6.1 },
    { name: 'Madagascar', code: 'MG', flag: '🇲🇬', lat: -18.7, lng: 46.8 },
    { name: 'Malaysia', code: 'MY', flag: '🇲🇾', lat: 4.2, lng: 101.9 },
    { name: 'Maldives', code: 'MV', flag: '🇲🇻', lat: 3.2, lng: 73.2 },
    { name: 'Malta', code: 'MT', flag: '🇲🇹', lat: 35.9, lng: 14.3 },
    { name: 'Mauritius', code: 'MU', flag: '🇲🇺', lat: -20.3, lng: 57.5 },
    { name: 'Mexico', code: 'MX', flag: '🇲🇽', lat: 23.6, lng: -102.5 },
    { name: 'Monaco', code: 'MC', flag: '🇲🇨', lat: 43.7, lng: 7.4 },
    { name: 'Mongolia', code: 'MN', flag: '🇲🇳', lat: 46.8, lng: 103.8 },
    { name: 'Montenegro', code: 'ME', flag: '🇲🇪', lat: 42.7, lng: 19.3 },
    { name: 'Morocco', code: 'MA', flag: '🇲🇦', lat: 31.7, lng: -7.0 },
    { name: 'Namibia', code: 'NA', flag: '🇳🇦', lat: -22.9, lng: 18.4 },
    { name: 'Nepal', code: 'NP', flag: '🇳🇵', lat: 28.3, lng: 84.1 },
    { name: 'Netherlands', code: 'NL', flag: '🇳🇱', lat: 52.1, lng: 5.2 },
    { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', lat: -40.9, lng: 174.8 },
    { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', lat: 12.8, lng: -85.2 },
    { name: 'Nigeria', code: 'NG', flag: '🇳🇬', lat: 9.0, lng: 8.6 },
    { name: 'Norway', code: 'NO', flag: '🇳🇴', lat: 60.4, lng: 8.4 },
    { name: 'Oman', code: 'OM', flag: '🇴🇲', lat: 21.4, lng: 55.9 },
    { name: 'Pakistan', code: 'PK', flag: '🇵🇰', lat: 30.3, lng: 69.3 },
    { name: 'Panama', code: 'PA', flag: '🇵🇦', lat: 8.5, lng: -80.7 },
    { name: 'Paraguay', code: 'PY', flag: '🇵🇾', lat: -23.4, lng: -58.4 },
    { name: 'Peru', code: 'PE', flag: '🇵🇪', lat: -9.1, lng: -75.0 },
    { name: 'Philippines', code: 'PH', flag: '🇵🇭', lat: 12.8, lng: 121.7 },
    { name: 'Poland', code: 'PL', flag: '🇵🇱', lat: 51.9, lng: 19.1 },
    { name: 'Portugal', code: 'PT', flag: '🇵🇹', lat: 39.3, lng: -8.2 },
    { name: 'Qatar', code: 'QA', flag: '🇶🇦', lat: 25.3, lng: 51.1 },
    { name: 'Romania', code: 'RO', flag: '🇷🇴', lat: 45.9, lng: 24.9 },
    { name: 'Russia', code: 'RU', flag: '🇷🇺', lat: 61.5, lng: 105.3 },
    { name: 'Rwanda', code: 'RW', flag: '🇷🇼', lat: -1.9, lng: 29.8 },
    { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', lat: 23.8, lng: 45.0 },
    { name: 'Senegal', code: 'SN', flag: '🇸🇳', lat: 14.4, lng: -14.4 },
    { name: 'Serbia', code: 'RS', flag: '🇷🇸', lat: 44.0, lng: 20.9 },
    { name: 'Seychelles', code: 'SC', flag: '🇸🇨', lat: -4.6, lng: 55.4 },
    { name: 'Singapore', code: 'SG', flag: '🇸🇬', lat: 1.3, lng: 103.8 },
    { name: 'Slovakia', code: 'SK', flag: '🇸🇰', lat: 48.6, lng: 19.6 },
    { name: 'Slovenia', code: 'SI', flag: '🇸🇮', lat: 46.1, lng: 14.9 },
    { name: 'South Africa', code: 'ZA', flag: '🇿🇦', lat: -30.5, lng: 22.9 },
    { name: 'South Korea', code: 'KR', flag: '🇰🇷', lat: 35.9, lng: 127.7 },
    { name: 'Spain', code: 'ES', flag: '🇪🇸', lat: 40.4, lng: -3.7 },
    { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', lat: 7.8, lng: 80.7 },
    { name: 'Sweden', code: 'SE', flag: '🇸🇪', lat: 60.1, lng: 18.6 },
    { name: 'Switzerland', code: 'CH', flag: '🇨🇭', lat: 46.8, lng: 8.2 },
    { name: 'Taiwan', code: 'TW', flag: '🇹🇼', lat: 23.6, lng: 120.9 },
    { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', lat: -6.3, lng: 34.8 },
    { name: 'Thailand', code: 'TH', flag: '🇹🇭', lat: 15.8, lng: 100.9 },
    { name: 'Tunisia', code: 'TN', flag: '🇹🇳', lat: 33.8, lng: 9.5 },
    { name: 'Turkey', code: 'TR', flag: '🇹🇷', lat: 38.9, lng: 35.2 },
    { name: 'Uganda', code: 'UG', flag: '🇺🇬', lat: 1.3, lng: 32.2 },
    { name: 'Ukraine', code: 'UA', flag: '🇺🇦', lat: 48.3, lng: 31.1 },
    { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', lat: 23.4, lng: 53.8 },
    { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', lat: 55.3, lng: -3.4 },
    { name: 'United States', code: 'US', flag: '🇺🇸', lat: 37.0, lng: -95.7 },
    { name: 'Uruguay', code: 'UY', flag: '🇺🇾', lat: -32.5, lng: -55.7 },
    { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', lat: 41.3, lng: 64.5 },
    { name: 'Vatican City', code: 'VA', flag: '🇻🇦', lat: 41.9, lng: 12.4 },
    { name: 'Venezuela', code: 'VE', flag: '🇻🇪', lat: 6.4, lng: -66.5 },
    { name: 'Vietnam', code: 'VN', flag: '🇻🇳', lat: 14.0, lng: 108.2 },
    { name: 'Zambia', code: 'ZM', flag: '🇿🇲', lat: -13.1, lng: 27.8 },
    { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', lat: -19.0, lng: 29.1 },
];
