export const COUNTRIES = [
    { name: 'Afghanistan', code: 'AF', flag: '🇦🇫' },
    { name: 'Albania', code: 'AL', flag: '🇦🇱' },
    { name: 'Algeria', code: 'DZ', flag: '🇩🇿' },
    { name: 'Andorra', code: 'AD', flag: '🇦🇩' },
    { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
    { name: 'Australia', code: 'AU', flag: '🇦🇺' },
    { name: 'Austria', code: 'AT', flag: '🇦🇹' },
    { name: 'Belgium', code: 'BE', flag: '🇧🇪' },
    { name: 'Brazil', code: 'BR', flag: '🇧🇷' },
    { name: 'Canada', code: 'CA', flag: '🇨🇦' },
    { name: 'China', code: 'CN', flag: '🇨🇳' },
    { name: 'Croatia', code: 'HR', flag: '🇭🇷' },
    { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
    { name: 'Denmark', code: 'DK', flag: '🇩🇰' },
    { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
    { name: 'Finland', code: 'FI', flag: '🇫🇮' },
    { name: 'France', code: 'FR', flag: '🇫🇷' },
    { name: 'Germany', code: 'DE', flag: '🇩🇪' },
    { name: 'Greece', code: 'GR', flag: '🇬🇷' },
    { name: 'Hungary', code: 'HU', flag: '🇭🇺' },
    { name: 'Iceland', code: 'IS', flag: '🇮🇸' },
    { name: 'India', code: 'IN', flag: '🇮🇳' },
    { name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
    { name: 'Ireland', code: 'IE', flag: '🇮🇪' },
    { name: 'Italy', code: 'IT', flag: '🇮🇹' },
    { name: 'Japan', code: 'JP', flag: '🇯🇵' },
    { name: 'Mexico', code: 'MX', flag: '🇲🇽' },
    { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
    { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
    { name: 'Norway', code: 'NO', flag: '🇳🇴' },
    { name: 'Poland', code: 'PL', flag: '🇵🇱' },
    { name: 'Portugal', code: 'PT', flag: '🇵🇹' },
    { name: 'Romania', code: 'RO', flag: '🇷🇴' },
    { name: 'Russia', code: 'RU', flag: '🇷🇺' },
    { name: 'Singapore', code: 'SG', flag: '🇸🇬' },
    { name: 'South Korea', code: 'KR', flag: '🇰🇷' },
    { name: 'Spain', code: 'ES', flag: '🇪🇸' },
    { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
    { name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
    { name: 'Thailand', code: 'TH', flag: '🇹🇭' },
    { name: 'Turkey', code: 'TR', flag: '🇹🇷' },
    { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
    { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
    { name: 'United States', code: 'US', flag: '🇺🇸' },
    { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
];
